In [83]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import zscore

In [140]:
#use just 4 years of data for now (2015 - 2018)
filenames = [('ucr_leoka_monthly_1960_2020_dta/leoka_monthly_' + str(i) + '.dta') for i in range(2016, 2019)]
filenames

['ucr_leoka_monthly_1960_2020_dta/leoka_monthly_2016.dta',
 'ucr_leoka_monthly_1960_2020_dta/leoka_monthly_2017.dta',
 'ucr_leoka_monthly_1960_2020_dta/leoka_monthly_2018.dta']

In [141]:
leoka_16, leoka_17, leoka_18 = pd.read_stata(filenames[0]), pd.read_stata(filenames[1]), pd.read_stata(filenames[2])
result = pd.concat([leoka_16, leoka_17, leoka_18], ignore_index=True)

In [94]:
result

,ori,agency_name,state,state_abb,number_of_months_reported,year,month,date,ori9,fips_state_code,...,other_patrols_day_shift,other_patrols_evening_shift,other_patrols_night_shift,other_patrols_other_shift,other_patrols_total_shift,total_patrols_veh_day_shift,total_patrols_evening_shift,total_patrols_night_shift,total_patrols_other_shift,total_patrols_total_shift
0,AK00101,anchorage,alaska,AK,12,2016,january,2016-01-01,AK0010100,02,...,0,0,0,0,0,0,0,0,0,0
1,AK00101,anchorage,alaska,AK,12,2016,february,2016-02-01,AK0010100,02,...,0,0,0,0,0,0,0,0,0,0
2,AK00101,anchorage,alaska,AK,12,2016,march,2016-03-01,AK0010100,02,...,0,0,0,0,0,0,0,0,0,0
3,AK00101,anchorage,alaska,AK,12,2016,april,2016-04-01,AK0010100,02,...,0,0,0,0,0,0,0,0,0,0
4,AK00101,anchorage,alaska,AK,12,2016,may,2016-05-01,AK0010100,02,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837595,WYWHP01,"highway patrol, cheyenne",wyoming,WY,0,2018,august,2018-08-01,,,...,0,0,0,0,0,0,0,0,0,0
837596,WYWHP01,"highway patrol, cheyenne",wyoming,WY,0,2018,september,2018-09-01,,,...,0,0,0,0,0,0,0,0,0,0
837597,WYWHP01,"highway patrol, cheyenne",wyoming,WY,0,2018,october,2018-10-01,,,...,0,0,0,0,0,0,0,0,0,0
837598,WYWHP01,"highway patrol, cheyenne",wyoming,WY,0,2018,november,2018-11-01,,,...,0,0,0,0,0,0,0,0,0,0
837599,WYWHP01,"highway patrol, cheyenne",wyoming,WY,0,2018,december,2018-12-01,,,...,0,0,0,0,0,0,0,0,0,0

In [95]:
result['year'] = result['year'].astype(int)

In [96]:
month_map = {'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5, 'june': 6, 'july': 7, 'august': 8, 'september': 9, 'october': 10, 'november': 11, 'december': 12}
result['month_code'] = result['month'].map(month_map) + (result['year'] - 2016)*12

/var/folders/5h/mg9jv4jj4_zc1dsmj4zsf1vm0000gn/T/ipykernel_75269/4034469824.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result['month_code'] = result['month'].map(month_map) + (result['year'] - 2016)*12

In [97]:
result['assaults_total'] = result['assaults_no_injury_total'] + result['assaults_with_injury_total']

/var/folders/5h/mg9jv4jj4_zc1dsmj4zsf1vm0000gn/T/ipykernel_75269/1120309183.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result['assaults_total'] = result['assaults_no_injury_total'] + result['assaults_with_injury_total']

In [98]:
mask = result.groupby('agency_name')['assaults_total'].transform(lambda x: any(x >= 1))
filtered_result = result[mask]

In [99]:
filtered_result.loc[filtered_result['officers_killed_total'] > 0]

,ori,agency_name,state,state_abb,number_of_months_reported,year,month,date,ori9,fips_state_code,...,other_patrols_night_shift,other_patrols_other_shift,other_patrols_total_shift,total_patrols_veh_day_shift,total_patrols_evening_shift,total_patrols_night_shift,total_patrols_other_shift,total_patrols_total_shift,month_code,assaults_total
21,AK00102,fairbanks,alaska,AK,12,2016,october,2016-10-01,AK0010200,02,...,0,0,0,0,0,0,0,0,10,1
203,AK00118,north slope borough,alaska,AK,12,2016,december,2016-12-01,AK0011800,02,...,0,0,0,0,0,0,0,0,12,1
6800,AR00801,berryville,arkansas,AR,12,2016,september,2016-09-01,AR0080100,05,...,0,0,0,0,0,0,0,0,9,0
10708,AZ00723,phoenix,arizona,AZ,12,2016,may,2016-05-01,AZ0072300,04,...,0,0,0,0,0,0,0,0,5,48
10765,AZ00733,wickenburg,arizona,AZ,12,2016,february,2016-02-01,AZ0073300,04,...,0,0,0,0,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816088,VA082SP,sp: rockingham county,virginia,VA,12,2018,may,2018-05-01,VA082SP00,51,...,0,0,0,0,0,0,0,0,29,0
816873,VA096SP,sp: wise county,virginia,VA,12,2018,october,2018-10-01,VA096SP00,51,...,0,0,0,0,0,0,0,0,34,0
817719,VA120SP,sp: portsmouth,virginia,VA,12,2018,april,2018-04-01,VA120SP00,51,...,0,0,0,0,0,0,0,0,28,0
823795,WADI056,makah tribal,washington,WA,12,2018,august,2018-08-01,WADI05600,53,...,0,0,0,0,0,0,0,0,32,1
829914,WIMPD00,milwaukee,wisconsin,WI,12,2018,july,2018-07-01,WIMPD0000,55,...,0,0,0,0,0,0,0,0,31,19

In [67]:
filtered_result = filtered_result.sort_values(by=['ori', 'month_code'])
filtered_result['post_1'] = 0
pos_treated_rows = filtered_result['officers_killed_total'] > 0
pos_treated_rows.value_counts()
filtered_result.groupby('ori')['post_1'].shift(1)
#filtered_result.loc[pos_treated_rows, 'post_1'] = filtered_result.groupby('ori')['post_1'].shift(1)
#filtered_result['post_1'].value_counts()
#filtered_result = filtered_result.reset_index(drop=True)

post_1
0.0    247703
Name: count, dtype: int64

In [104]:
filtered_result = filtered_result.sort_values(by=['ori', 'month_code'])
filtered_result['post_1'] = 0
filtered_result['post_2'] = 0
filtered_result['post_3'] = 0
filtered_result['post_4'] = 0
filtered_result['post_5'] = 0
filtered_result['post_6'] = 0
filtered_result['post_6+'] = 0

for idx, row in filtered_result.iterrows():
    try:
        next_index, idx_2, idx_3, idx_4, idx_5, idx_6 = idx+1, idx+2, idx+3, idx+4, idx+5, idx+6
        if next_index < len(filtered_result):
            next_row = filtered_result.loc[next_index]
            if row['officers_killed_total'] > 0 and next_row['ori'] == row['ori']:
                filtered_result.at[next_index, 'post_1'] = 1

        idx_2 = idx+2
        if idx_2 < len(filtered_result):
            row_2 = filtered_result.loc[idx_2]
            if row['officers_killed_total'] > 0 and row_2['ori'] == row['ori']:
                filtered_result.at[idx_2, 'post_2'] = 1

        idx_3 = idx+3
        if idx_3 < len(filtered_result):
            row_3 = filtered_result.loc[idx_3]
            if row['officers_killed_total'] > 0 and row_3['ori'] == row['ori']:
                filtered_result.at[idx_3, 'post_3'] = 1

        idx_4 = idx+4
        if idx_4 < len(filtered_result):
            row_4 = filtered_result.loc[idx_4]
            if row['officers_killed_total'] > 0 and row_4['ori'] == row['ori']:
                filtered_result.at[idx_4, 'post_4'] = 1

        idx_5 = idx+5
        if idx_5 < len(filtered_result):
            row_5 = filtered_result.loc[idx_5]
            if row['officers_killed_total'] > 0 and row_5['ori'] == row['ori']:
                filtered_result.at[idx_5, 'post_5'] = 1

        idx_6 = idx+6
        if idx_6 < len(filtered_result):
            row_6 = filtered_result.loc[idx_6]
            if row['officers_killed_total'] > 0 and row_6['ori'] == row['ori']:
                filtered_result.at[idx_6, 'post_6'] = 1
    except:
        continue
    
    #try:
    #    j = idx+7
    #    while filtered_result.loc[j]['ori'] == row['ori']:
    #        filtered_result.at[j, 'post_6+'] = 1
    #        j += 1
    #except:
    #    break

In [112]:
#z-scored sizes
filtered_result['force_size_scored'] = zscore(filtered_result['total_employees_officers'])

In [113]:
arrest_files = ['ucr_arrests_monthly_index_1974_2018_dta/ucr_arrests_monthly_index_crimes_age_2016.dta', 'ucr_arrests_monthly_index_1974_2018_dta/ucr_arrests_monthly_index_crimes_age_2017.dta', 'ucr_arrests_monthly_index_1974_2018_dta/ucr_arrests_monthly_index_crimes_age_2018.dta']
arrests_16 = pd.read_stata(arrest_files[0])
arrests_17 = pd.read_stata(arrest_files[1])
arrests_18 = pd.read_stata(arrest_files[2])
arrests = pd.concat([arrests_16, arrests_17, arrests_18], ignore_index=True)

In [114]:
arrests['total_arrests'] = arrests['theft_tot_arrests'] + arrests['robbery_tot_arrests'] + arrests['rape_tot_arrests'] + arrests['murder_tot_arrests'] + arrests['mtr_veh_theft_tot_arrests'] + arrests['burglary_tot_arrests'] + arrests['arson_tot_arrests'] + arrests['agg_assault_tot_arrests']
arrests['year'] = arrests['year'].astype(int)

/var/folders/5h/mg9jv4jj4_zc1dsmj4zsf1vm0000gn/T/ipykernel_75269/3593767019.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  arrests['total_arrests'] = arrests['theft_tot_arrests'] + arrests['robbery_tot_arrests'] + arrests['rape_tot_arrests'] + arrests['murder_tot_arrests'] + arrests['mtr_veh_theft_tot_arrests'] + arrests['burglary_tot_arrests'] + arrests['arson_tot_arrests'] + arrests['agg_assault_tot_arrests']

In [115]:
agg_result = pd.merge(filtered_result, arrests, on=['ori', 'month', 'year'], how='left')

In [116]:
agg_result['total_arrests'] = agg_result['total_arrests'].fillna(0)
agg_result['assault_indicator'] = (agg_result['assaults_total'] > 0).astype(int)

In [119]:
agg_result = agg_result.drop('post_6+', axis=1)

In [142]:
agg_cleaned = agg_result.dropna()

In [144]:
agg_cleaned.to_stata('a8.dta')

ValueError: Column `msa` cannot be exported.

Only string-like object arrays
containing all strings or a mix of strings and None can be exported.
Object arrays containing only null values are prohibited. Other object
types cannot be exported and must first be converted to one of the
supported types.

In [145]:
for i in agg_cleaned.columns:
    print(i)

ori
agency_name_x
state_x
state_abb_x
number_of_months_reported_x
year
month
date
ori9_x
fips_state_code_x
fips_county_code_x
fips_state_county_code_x
fips_place_code_x
agency_type
crosswalk_agency_name
census_name
longitude
latitude
address_name
address_street_line_1
address_street_line_2
address_city
address_state
address_zip_code
population_x
population_group_x
country_division_x
msa
report_indicator
record_indicator
month_indicator
covered_by_x
shift_data
no_male_female_breakdown
assault_injury_indicator
assault_no_injury_indicator
male_employees_officers
female_employees_officers
total_employees_officers
male_employees_civilians
female_employees_civilians
total_employees_civilians
male_employees_total
female_employees_total
total_employees_total
officers_killed_total
officers_killed_by_felony
officers_killed_by_accident
assaults_with_injury_gun
assaults_with_injury_knife
assaults_with_injury_oth_weap
assaults_with_injury_unarmed
assaults_with_injury_total
assaults_no_injury_gun
assaults_no_injury_knife
assaults_no_injury_oth_weap
assaults_no_injury_unarmed
assaults_no_injury_total
ambush_total_assaults
ambush_assault_gun
ambush_assault_knife
ambush_assault_oth_weap
ambush_assault_unarmed
ambush_two_man_veh
ambush_one_man_alone
ambush_one_man_assist
ambush_detective_alone
ambush_detective_assist
ambush_other_alone
ambush_other_assist
ambush_assaults_cleared
oth_arrest_total_assaults
oth_arrest_assault_gun
oth_arrest_assault_knife
oth_arrest_assault_oth_weap
oth_arrest_assault_unarmed
oth_arrest_two_man_veh
oth_arrest_one_man_alone
oth_arrest_one_man_assist
oth_arrest_detective_alone
oth_arrest_detective_assist
oth_arrest_other_alone
oth_arrest_other_assist
oth_arrest_assaults_cleared
burglary_total_assaults
burglary_assault_gun
burglary_assault_knife
burglary_assault_oth_weap
burglary_assault_unarmed
burglary_two_man_veh
burglary_one_man_alone
burglary_one_man_assist
burglary_detective_alone
burglary_detective_assist
burglary_other_alone
burglary_other_assist
burglary_assaults_cleared
deranged_total_assaults
deranged_assault_gun
deranged_assault_knife
deranged_assault_oth_weap
deranged_assault_unarmed
deranged_two_man_veh
deranged_one_man_alone
deranged_one_man_assist
deranged_detective_alone
deranged_detective_assist
deranged_other_alone
deranged_other_assist
deranged_assaults_cleared
disturbance_total_assaults
disturbance_assault_gun
disturbance_assault_knife
disturbance_assault_oth_weap
disturbance_assault_unarmed
disturbance_two_man_veh
disturbance_one_man_alone
disturbance_one_man_assist
disturbance_detective_alone
disturbance_detective_assist
disturbance_other_alone
disturbance_other_assist
disturbance_assaults_cleared
prisoner_total_assaults
prisoner_assault_gun
prisoner_assault_knife
prisoner_assault_oth_weap
prisoner_assault_unarmed
prisoner_two_man_veh
prisoner_one_man_alone
prisoner_one_man_assist
prisoner_detective_alone
prisoner_detective_assist
prisoner_other_alone
prisoner_other_assist
prisoner_assaults_cleared
riot_total_assaults
riot_assault_gun
riot_assault_knife
riot_assault_oth_weap
riot_assault_unarmed
riot_two_man_veh
riot_one_man_alone
riot_one_man_assist
riot_detective_alone
riot_detective_assiste
riot_other_alone
riot_other_assist
riot_assaults_cleared
robbery_total_assaults
robbery_assault_gun
robbery_assault_knife
robbery_assault_oth_weap
robbery_assault_unarmed
robbery_two_man_veh
robbery_one_man_alone
robbery_one_man_assist
robbery_detective_alone
robbery_detective_assist
robbery_other_alone
robbery_other_assist
robbery_assaults_cleared
susp_pers_total_assaults
susp_pers_assault_gun
susp_pers_assault_knife
susp_pers_assault_oth_weap
susp_pers_assault_unarmed
susp_pers_two_man_veh
susp_pers_one_man_alone
susp_pers_one_man_assist
susp_pers_detective_alone
susp_pers_detective_assist
susp_pers_other_alone
susp_pers_other_assist
susp_pers_assaults_cleared
traffic_total_assaults
traffic_assault_gun
traffic_assault_knife
traffic_assault_oth_weap
traffic_assault_unarmed
traffic_two_man_veh
traffic_one_man_alone
traffic_one_man_assist
traffic_detective_alone
traffic_detective_assist
traffic_other_alone
traffic_other_assist
traffic_assaults_cleared
all_other_total_assaults
all_other_assault_gun
all_other_assault_knife
all_other_assault_oth_weap
all_other_assault_unarmed
all_other_two_man_veh
all_other_one_man_alone
all_other_one_man_assist
all_other_detective_alone
all_other_detective_assist
all_other_other_alone
all_other_other_assist
all_other_assaults_cleared
total_assaults_total
total_assault_gun
total_assault_knife
total_assault_oth_weap
total_assault_unarmed
total_two_man_veh
total_one_man_alone
total_one_man_assist
total_detective_alone
total_detective_assist
total_other_alone
total_other_assist
total_assaults_cleared
time_of_assault_0001_to_0200
time_of_assault_0201_to_0400
time_of_assault_0401_to_0600
time_of_assault_0601_to_0800
time_of_assault_0801_to_1000
time_of_assault_1001_to_1200
time_of_assault_1201_to_1400
time_of_assault_1401_to_1600
time_of_assault_1601_to_1800
time_of_assault_1801_to_2000
time_of_assault_2001_to_2200
time_of_assault_2201_to_0000
one_man_veh_day_shift
one_man_veh_evening_shift
one_man_veh_night_shift
one_man_veh_other_shift
one_man_veh_total_shift
two_man_veh_day_shift
two_man_veh_evening_shift
two_man_veh_night_shift
two_man_veh_other_shift
two_man_veh_total_shift
one_man_foot_day_shift
one_man_foot_evening_shift
one_man_foot_night_shift
one_man_foot_other_shift
one_man_foot_total_shift
two_man_foot_day_shift
two_man_foot_evening_shift
two_man_foot_night_shift
two_man_foot_other_shift
two_man_foot_total_shift
other_patrols_day_shift
other_patrols_evening_shift
other_patrols_night_shift
other_patrols_other_shift
other_patrols_total_shift
total_patrols_veh_day_shift
total_patrols_evening_shift
total_patrols_night_shift
total_patrols_other_shift
total_patrols_total_shift
month_code
assaults_total
post_1
post_2
post_3
post_4
post_5
post_6
force_size_scored
ori9_y
number_of_months_reported_y
num_months_murder
num_months_rape
num_months_robbery
num_months_agg_assault
num_months_burglary
num_months_theft
num_months_mtr_veh_theft
num_months_arson
population_y
agency_name_y
state_y
state_abb_y
population_group_y
country_division_y
fips_state_code_y
fips_county_code_y
fips_state_county_code_y
fips_place_code_y
covered_by_y
agg_assault_female_10_12
agg_assault_female_13_14
agg_assault_female_15
agg_assault_female_16
agg_assault_female_17
agg_assault_female_18
agg_assault_female_19
agg_assault_female_20
agg_assault_female_21
agg_assault_female_22
agg_assault_female_23
agg_assault_female_24
agg_assault_female_25_29
agg_assault_female_30_34
agg_assault_female_35_39
agg_assault_female_40_44
agg_assault_female_45_49
agg_assault_female_50_54
agg_assault_female_55_59
agg_assault_female_60_64
agg_assault_female_over_64
agg_assault_female_under_10
agg_assault_male_10_12
agg_assault_male_13_14
agg_assault_male_15
agg_assault_male_16
agg_assault_male_17
agg_assault_male_18
agg_assault_male_19
agg_assault_male_20
agg_assault_male_21
agg_assault_male_22
agg_assault_male_23
agg_assault_male_24
agg_assault_male_25_29
agg_assault_male_30_34
agg_assault_male_35_39
agg_assault_male_40_44
agg_assault_male_45_49
agg_assault_male_50_54
agg_assault_male_55_59
agg_assault_male_60_64
agg_assault_male_over_64
agg_assault_male_under_10
agg_assault_tot_10_12
agg_assault_tot_13_14
agg_assault_tot_15
agg_assault_tot_16
agg_assault_tot_17
agg_assault_tot_18
agg_assault_tot_19
agg_assault_tot_20
agg_assault_tot_21
agg_assault_tot_22
agg_assault_tot_23
agg_assault_tot_24
agg_assault_tot_25_29
agg_assault_tot_30_34
agg_assault_tot_35_39
agg_assault_tot_40_44
agg_assault_tot_45_49
agg_assault_tot_50_54
agg_assault_tot_55_59
agg_assault_tot_60_64
agg_assault_tot_adult
agg_assault_tot_arrests
agg_assault_tot_female
agg_assault_tot_female_adult
agg_assault_tot_female_juv
agg_assault_tot_juv
agg_assault_tot_male
agg_assault_tot_male_adult
agg_assault_tot_male_juv
agg_assault_tot_over_64
agg_assault_tot_under_10
arson_female_10_12
arson_female_13_14
arson_female_15
arson_female_16
arson_female_17
arson_female_18
arson_female_19
arson_female_20
arson_female_21
arson_female_22
arson_female_23
arson_female_24
arson_female_25_29
arson_female_30_34
arson_female_35_39
arson_female_40_44
arson_female_45_49
arson_female_50_54
arson_female_55_59
arson_female_60_64
arson_female_over_64
arson_female_under_10
arson_male_10_12
arson_male_13_14
arson_male_15
arson_male_16
arson_male_17
arson_male_18
arson_male_19
arson_male_20
arson_male_21
arson_male_22
arson_male_23
arson_male_24
arson_male_25_29
arson_male_30_34
arson_male_35_39
arson_male_40_44
arson_male_45_49
arson_male_50_54
arson_male_55_59
arson_male_60_64
arson_male_over_64
arson_male_under_10
arson_tot_10_12
arson_tot_13_14
arson_tot_15
arson_tot_16
arson_tot_17
arson_tot_18
arson_tot_19
arson_tot_20
arson_tot_21
arson_tot_22
arson_tot_23
arson_tot_24
arson_tot_25_29
arson_tot_30_34
arson_tot_35_39
arson_tot_40_44
arson_tot_45_49
arson_tot_50_54
arson_tot_55_59
arson_tot_60_64
arson_tot_adult
arson_tot_arrests
arson_tot_female
arson_tot_female_adult
arson_tot_female_juv
arson_tot_juv
arson_tot_male
arson_tot_male_adult
arson_tot_male_juv
arson_tot_over_64
arson_tot_under_10
burglary_female_10_12
burglary_female_13_14
burglary_female_15
burglary_female_16
burglary_female_17
burglary_female_18
burglary_female_19
burglary_female_20
burglary_female_21
burglary_female_22
burglary_female_23
burglary_female_24
burglary_female_25_29
burglary_female_30_34
burglary_female_35_39
burglary_female_40_44
burglary_female_45_49
burglary_female_50_54
burglary_female_55_59
burglary_female_60_64
burglary_female_over_64
burglary_female_under_10
burglary_male_10_12
burglary_male_13_14
burglary_male_15
burglary_male_16
burglary_male_17
burglary_male_18
burglary_male_19
burglary_male_20
burglary_male_21
burglary_male_22
burglary_male_23
burglary_male_24
burglary_male_25_29
burglary_male_30_34
burglary_male_35_39
burglary_male_40_44
burglary_male_45_49
burglary_male_50_54
burglary_male_55_59
burglary_male_60_64
burglary_male_over_64
burglary_male_under_10
burglary_tot_10_12
burglary_tot_13_14
burglary_tot_15
burglary_tot_16
burglary_tot_17
burglary_tot_18
burglary_tot_19
burglary_tot_20
burglary_tot_21
burglary_tot_22
burglary_tot_23
burglary_tot_24
burglary_tot_25_29
burglary_tot_30_34
burglary_tot_35_39
burglary_tot_40_44
burglary_tot_45_49
burglary_tot_50_54
burglary_tot_55_59
burglary_tot_60_64
burglary_tot_adult
burglary_tot_arrests
burglary_tot_female
burglary_tot_female_adult
burglary_tot_female_juv
burglary_tot_juv
burglary_tot_male
burglary_tot_male_adult
burglary_tot_male_juv
burglary_tot_over_64
burglary_tot_under_10
mtr_veh_theft_female_10_12
mtr_veh_theft_female_13_14
mtr_veh_theft_female_15
mtr_veh_theft_female_16
mtr_veh_theft_female_17
mtr_veh_theft_female_18
mtr_veh_theft_female_19
mtr_veh_theft_female_20
mtr_veh_theft_female_21
mtr_veh_theft_female_22
mtr_veh_theft_female_23
mtr_veh_theft_female_24
mtr_veh_theft_female_25_29
mtr_veh_theft_female_30_34
mtr_veh_theft_female_35_39
mtr_veh_theft_female_40_44
mtr_veh_theft_female_45_49
mtr_veh_theft_female_50_54
mtr_veh_theft_female_55_59
mtr_veh_theft_female_60_64
mtr_veh_theft_female_over_64
mtr_veh_theft_female_under_10
mtr_veh_theft_male_10_12
mtr_veh_theft_male_13_14
mtr_veh_theft_male_15
mtr_veh_theft_male_16
mtr_veh_theft_male_17
mtr_veh_theft_male_18
mtr_veh_theft_male_19
mtr_veh_theft_male_20
mtr_veh_theft_male_21
mtr_veh_theft_male_22
mtr_veh_theft_male_23
mtr_veh_theft_male_24
mtr_veh_theft_male_25_29
mtr_veh_theft_male_30_34
mtr_veh_theft_male_35_39
mtr_veh_theft_male_40_44
mtr_veh_theft_male_45_49
mtr_veh_theft_male_50_54
mtr_veh_theft_male_55_59
mtr_veh_theft_male_60_64
mtr_veh_theft_male_over_64
mtr_veh_theft_male_under_10
mtr_veh_theft_tot_10_12
mtr_veh_theft_tot_13_14
mtr_veh_theft_tot_15
mtr_veh_theft_tot_16
mtr_veh_theft_tot_17
mtr_veh_theft_tot_18
mtr_veh_theft_tot_19
mtr_veh_theft_tot_20
mtr_veh_theft_tot_21
mtr_veh_theft_tot_22
mtr_veh_theft_tot_23
mtr_veh_theft_tot_24
mtr_veh_theft_tot_25_29
mtr_veh_theft_tot_30_34
mtr_veh_theft_tot_35_39
mtr_veh_theft_tot_40_44
mtr_veh_theft_tot_45_49
mtr_veh_theft_tot_50_54
mtr_veh_theft_tot_55_59
mtr_veh_theft_tot_60_64
mtr_veh_theft_tot_adult
mtr_veh_theft_tot_arrests
mtr_veh_theft_tot_female
mtr_veh_theft_tot_female_adult
mtr_veh_theft_tot_female_juv
mtr_veh_theft_tot_juv
mtr_veh_theft_tot_male
mtr_veh_theft_tot_male_adult
mtr_veh_theft_tot_male_juv
mtr_veh_theft_tot_over_64
mtr_veh_theft_tot_under_10
murder_female_10_12
murder_female_13_14
murder_female_15
murder_female_16
murder_female_17
murder_female_18
murder_female_19
murder_female_20
murder_female_21
murder_female_22
murder_female_23
murder_female_24
murder_female_25_29
murder_female_30_34
murder_female_35_39
murder_female_40_44
murder_female_45_49
murder_female_50_54
murder_female_55_59
murder_female_60_64
murder_female_over_64
murder_female_under_10
murder_male_10_12
murder_male_13_14
murder_male_15
murder_male_16
murder_male_17
murder_male_18
murder_male_19
murder_male_20
murder_male_21
murder_male_22
murder_male_23
murder_male_24
murder_male_25_29
murder_male_30_34
murder_male_35_39
murder_male_40_44
murder_male_45_49
murder_male_50_54
murder_male_55_59
murder_male_60_64
murder_male_over_64
murder_male_under_10
murder_tot_10_12
murder_tot_13_14
murder_tot_15
murder_tot_16
murder_tot_17
murder_tot_18
murder_tot_19
murder_tot_20
murder_tot_21
murder_tot_22
murder_tot_23
murder_tot_24
murder_tot_25_29
murder_tot_30_34
murder_tot_35_39
murder_tot_40_44
murder_tot_45_49
murder_tot_50_54
murder_tot_55_59
murder_tot_60_64
murder_tot_adult
murder_tot_arrests
murder_tot_female
murder_tot_female_adult
murder_tot_female_juv
murder_tot_juv
murder_tot_male
murder_tot_male_adult
murder_tot_male_juv
murder_tot_over_64
murder_tot_under_10
rape_female_10_12
rape_female_13_14
rape_female_15
rape_female_16
rape_female_17
rape_female_18
rape_female_19
rape_female_20
rape_female_21
rape_female_22
rape_female_23
rape_female_24
rape_female_25_29
rape_female_30_34
rape_female_35_39
rape_female_40_44
rape_female_45_49
rape_female_50_54
rape_female_55_59
rape_female_60_64
rape_female_over_64
rape_female_under_10
rape_male_10_12
rape_male_13_14
rape_male_15
rape_male_16
rape_male_17
rape_male_18
rape_male_19
rape_male_20
rape_male_21
rape_male_22
rape_male_23
rape_male_24
rape_male_25_29
rape_male_30_34
rape_male_35_39
rape_male_40_44
rape_male_45_49
rape_male_50_54
rape_male_55_59
rape_male_60_64
rape_male_over_64
rape_male_under_10
rape_tot_10_12
rape_tot_13_14
rape_tot_15
rape_tot_16
rape_tot_17
rape_tot_18
rape_tot_19
rape_tot_20
rape_tot_21
rape_tot_22
rape_tot_23
rape_tot_24
rape_tot_25_29
rape_tot_30_34
rape_tot_35_39
rape_tot_40_44
rape_tot_45_49
rape_tot_50_54
rape_tot_55_59
rape_tot_60_64
rape_tot_adult
rape_tot_arrests
rape_tot_female
rape_tot_female_adult
rape_tot_female_juv
rape_tot_juv
rape_tot_male
rape_tot_male_adult
rape_tot_male_juv
rape_tot_over_64
rape_tot_under_10
robbery_female_10_12
robbery_female_13_14
robbery_female_15
robbery_female_16
robbery_female_17
robbery_female_18
robbery_female_19
robbery_female_20
robbery_female_21
robbery_female_22
robbery_female_23
robbery_female_24
robbery_female_25_29
robbery_female_30_34
robbery_female_35_39
robbery_female_40_44
robbery_female_45_49
robbery_female_50_54
robbery_female_55_59
robbery_female_60_64
robbery_female_over_64
robbery_female_under_10
robbery_male_10_12
robbery_male_13_14
robbery_male_15
robbery_male_16
robbery_male_17
robbery_male_18
robbery_male_19
robbery_male_20
robbery_male_21
robbery_male_22
robbery_male_23
robbery_male_24
robbery_male_25_29
robbery_male_30_34
robbery_male_35_39
robbery_male_40_44
robbery_male_45_49
robbery_male_50_54
robbery_male_55_59
robbery_male_60_64
robbery_male_over_64
robbery_male_under_10
robbery_tot_10_12
robbery_tot_13_14
robbery_tot_15
robbery_tot_16
robbery_tot_17
robbery_tot_18
robbery_tot_19
robbery_tot_20
robbery_tot_21
robbery_tot_22
robbery_tot_23
robbery_tot_24
robbery_tot_25_29
robbery_tot_30_34
robbery_tot_35_39
robbery_tot_40_44
robbery_tot_45_49
robbery_tot_50_54
robbery_tot_55_59
robbery_tot_60_64
robbery_tot_adult
robbery_tot_arrests
robbery_tot_female
robbery_tot_female_adult
robbery_tot_female_juv
robbery_tot_juv
robbery_tot_male
robbery_tot_male_adult
robbery_tot_male_juv
robbery_tot_over_64
robbery_tot_under_10
theft_female_10_12
theft_female_13_14
theft_female_15
theft_female_16
theft_female_17
theft_female_18
theft_female_19
theft_female_20
theft_female_21
theft_female_22
theft_female_23
theft_female_24
theft_female_25_29
theft_female_30_34
theft_female_35_39
theft_female_40_44
theft_female_45_49
theft_female_50_54
theft_female_55_59
theft_female_60_64
theft_female_over_64
theft_female_under_10
theft_male_10_12
theft_male_13_14
theft_male_15
theft_male_16
theft_male_17
theft_male_18
theft_male_19
theft_male_20
theft_male_21
theft_male_22
theft_male_23
theft_male_24
theft_male_25_29
theft_male_30_34
theft_male_35_39
theft_male_40_44
theft_male_45_49
theft_male_50_54
theft_male_55_59
theft_male_60_64
theft_male_over_64
theft_male_under_10
theft_tot_10_12
theft_tot_13_14
theft_tot_15
theft_tot_16
theft_tot_17
theft_tot_18
theft_tot_19
theft_tot_20
theft_tot_21
theft_tot_22
theft_tot_23
theft_tot_24
theft_tot_25_29
theft_tot_30_34
theft_tot_35_39
theft_tot_40_44
theft_tot_45_49
theft_tot_50_54
theft_tot_55_59
theft_tot_60_64
theft_tot_adult
theft_tot_arrests
theft_tot_female
theft_tot_female_adult
theft_tot_female_juv
theft_tot_juv
theft_tot_male
theft_tot_male_adult
theft_tot_male_juv
theft_tot_over_64
theft_tot_under_10
juv_handled_within_department
juv_referred_to_juv_court
juv_referred_to_welfare
juv_referred_to_police
juv_referred_to_crim_court
total_arrests
assault_indicator

In [148]:
#summary statistics
agg_cleaned.describe()

,number_of_months_reported_x,year,population_x,male_employees_officers,female_employees_officers,total_employees_officers,male_employees_civilians,female_employees_civilians,total_employees_civilians,male_employees_total,...,theft_tot_male_juv,theft_tot_over_64,theft_tot_under_10,juv_handled_within_department,juv_referred_to_juv_court,juv_referred_to_welfare,juv_referred_to_police,juv_referred_to_crim_court,total_arrests,assault_indicator
count,179522.000000,179522.000000,1.795220e+05,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,...,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000,179522.000000
mean,11.808057,2017.142662,4.335645e+04,73.836343,10.382700,84.219043,13.788951,20.975786,34.764736,87.625294,...,0.812318,0.114175,0.005409,1.032692,2.217633,0.042998,0.108137,0.214670,20.970550,0.249240
std,1.193674,0.830440,1.206432e+05,275.082269,52.729973,324.701097,68.495457,90.787090,155.873594,327.865704,...,2.615514,0.450172,0.085871,8.373690,31.618173,1.795136,5.931771,2.563458,58.775033,0.432574
min,0.000000,2016.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,2016.000000,6.401000e+03,12.000000,0.000000,13.000000,0.000000,1.000000,1.000000,13.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
50%,12.000000,2017.000000,1.678100e+04,27.000000,2.000000,29.000000,2.000000,5.000000,7.000000,30.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000
75%,12.000000,2018.000000,4.100700e+04,59.000000,6.000000,65.000000,8.000000,16.000000,24.000000,70.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,0.000000
max,12.000000,2018.000000,4.029741e+06,8146.000000,1842.000000,9988.000000,2864.000000,4541.000000,7405.000000,10487.000000,...,91.000000,15.000000,5.000000,705.000000,6475.000000,350.000000,871.000000,261.000000,1871.000000,1.000000

In [149]:
selected_columns = ['population_x', 'total_employees_officers', 'assaults_total', 'officers_killed_total', 'total_arrests']
summary_stats = agg_cleaned[selected_columns].describe()

In [157]:
summary_stats = summary_stats.transpose()
latex_code = summary_stats.to_latex()

In [158]:
print(latex_code)

\begin{tabular}{lrrrrrrrr}
\toprule
 & count & mean & std & min & 25% & 50% & 75% & max \\
\midrule
population_x & 179522.000000 & 43356.449822 & 120643.171292 & 0.000000 & 6401.000000 & 16781.000000 & 41007.000000 & 4029741.000000 \\
total_employees_officers & 179522.000000 & 84.219043 & 324.701097 & 0.000000 & 13.000000 & 29.000000 & 65.000000 & 9988.000000 \\
assaults_total & 179522.000000 & 0.905482 & 4.000618 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 318.000000 \\
officers_killed_total & 179522.000000 & 0.000819 & 0.033617 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 5.000000 \\
total_arrests & 179522.000000 & 20.970550 & 58.775033 & 0.000000 & 2.000000 & 6.000000 & 19.000000 & 1871.000000 \\
\bottomrule
\end{tabular}